services:
  - type: web
    name: habitability-api
    env: python
    branch: vidhya
    rootDir: notebook/api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10.11

  - type: web
    name: habitability-frontend
    env: python
    branch: vidhya
    rootDir: frontend
    buildCommand: pip install -r requirements.txt
    startCommand: >
      streamlit run streamlit_app.py
      --server.port $PORT
      --server.address 0.0.0.0
    pythonVersion: 3.10.11
